Repository forestry-labs/Rforestry, pull requests merged in 2023-03, with the labels that each got.

#62 Improvements for releases
  .github/release.yml
  .github/workflows/python.yaml
  README.md
Labels: CI/CD

#60 Custom sampling
  Python/extension/src/api.cpp
  R/DESCRIPTION
  R/R/RcppExports.R
  R/R/forestry.R
  R/man/forestry.Rd
  R/man/training_data_checker-forestry.Rd
  R/tests/testthat/test-advancedCustomSampling.R
  R/tests/testthat/test-customSample.R
  src/RcppExports.cpp
  src/dataFrame.cpp
  src/dataFrame.h
  src/forestry.cpp
  src/forestry.h
  src/forestryTree.cpp
  src/forestryTree.h
  src/rcpp_cppBuildInterface.cpp
  src/utils.h
Labels: R, C++

#63 New VI Metrics
  R/DESCRIPTION
  R/NAMESPACE
  R/R/forestry.R
  R/man/getVI-forestry.Rd
  R/tests/testthat/test-alternateVI.R
Labels: R

#77 Rename custom sampling parameters and comment out debug logs
  Python/extension/src/api.cpp
  R/DESCRIPTION
  R/R/RcppExports.R
  R/R/forestry.R
  R/man/forestry.Rd
  R/man/training_data_checker-forestry.Rd
  R/tests/testthat/test-advancedCustomSampling.R
  R/tests/testthat/test-customSample.R
  src/RFNode.cpp
  src/RcppExports.cpp
  src/dataFrame.cpp
  src/dataFrame.h
  src/forestry.cpp
  src/rcpp_cppBuildInterface.cpp
  src/utils.cpp
Labels: R, C++

#80 Align package version between R and Python
  Python/LICENSE
  Python/pyproject.toml
Labels: ignore-for-release, Python

#81 Bump python package version to 0.10.0
  Python/pyproject.toml
  Python/random_forestry/__init__.py
Labels: ignore-for-release, Python

#83 Allow upload of python packages to Test Pypi
  .github/workflows/R.yaml
  .github/workflows/python.yaml
Labels: ignore-for-release, CI/CD
